// frontend/src/template/tailAdmin/layout/AppSidebar.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useLocation } from "react-router-dom";

import { FiChevronDown,  FiMoreHorizontal} from "react-icons/fi";

import { useSidebar } from "../context/SidebarContext";
import SidebarWidget from "./SidebarWidget";
import AppVersion from "../../../shared/components/AppVersion";

export type NavItem = {
  name: string;
  icon: React.ReactNode;
  path?: string;
  subItems?: { name: string; path: string; pro?: boolean; new?: boolean }[];
};

export type AppSidebarBranding = {
  href?: string;
  expandedLightSrc?: string;
  expandedDarkSrc?: string;
  collapsedSrc?: string;
  alt?: string;
  expandedWidth?: number;
  expandedHeight?: number;
  collapsedSize?: number;
};

const defaultNavItems: NavItem[] = [];

const defaultOthersItems: NavItem[] = [];

export type AppSidebarProps = {
  navItems?: NavItem[];
  othersItems?: NavItem[];
  branding?: AppSidebarBranding;
};

const AppSidebar: React.FC<AppSidebarProps> = ({
  navItems = defaultNavItems,
  othersItems = defaultOthersItems,
  branding,
}) => {
  const { isExpanded, isMobileOpen, isHovered, setIsHovered } = useSidebar();
  const location = useLocation();

  const [openSubmenu, setOpenSubmenu] = useState<{
    type: "main" | "others";
    index: number;
  } | null>(null);
  const [subMenuHeight, setSubMenuHeight] = useState<Record<string, number>>(
    {}
  );
  const subMenuRefs = useRef<Record<string, HTMLDivElement | null>>({});

  // const isActive = (path: string) => location.pathname === path;
  const isActive = useCallback(
    (path: string) => location.pathname === path,
    [location.pathname]
  );

  useEffect(() => {
    let submenuMatched = false;
    ["main", "others"].forEach((menuType) => {
      const items = menuType === "main" ? navItems : othersItems;
      items.forEach((nav, index) => {
        if (nav.subItems) {
          nav.subItems.forEach((subItem) => {
            if (isActive(subItem.path)) {
              setOpenSubmenu({
                type: menuType as "main" | "others",
                index,
              });
              submenuMatched = true;
            }
          });
        }
      });
    });

    if (!submenuMatched) {
      setOpenSubmenu(null);
    }
  }, [location, isActive]);

  useEffect(() => {
    if (openSubmenu !== null) {
      const key = `${openSubmenu.type}-${openSubmenu.index}`;
      if (subMenuRefs.current[key]) {
        setSubMenuHeight((prevHeights) => ({
          ...prevHeights,
          [key]: subMenuRefs.current[key]?.scrollHeight || 0,
        }));
      }
    }
  }, [openSubmenu]);

  const handleSubmenuToggle = (index: number, menuType: "main" | "others") => {
    setOpenSubmenu((prevOpenSubmenu) => {
      if (
        prevOpenSubmenu &&
        prevOpenSubmenu.type === menuType &&
        prevOpenSubmenu.index === index
      ) {
        return null;
      }
      return { type: menuType, index };
    });
  };

  const hasOthersSection = othersItems.some(
    (item) => Boolean(item.path) || Boolean(item.subItems?.length)
  );

  const renderMenuItems = (items: NavItem[], menuType: "main" | "others") => (
    <ul className="flex flex-col gap-4">
      {items.map((nav, index) => (
        <li key={nav.name}>
          {nav.subItems ? (
            <button
              onClick={() => handleSubmenuToggle(index, menuType)}
              className={`menu-item group ${
                openSubmenu?.type === menuType && openSubmenu?.index === index
                  ? "menu-item-active"
                  : "menu-item-inactive"
              } flex w-full items-center gap-3 cursor-pointer ${
                !isExpanded && !isHovered
                  ? "justify-center"
                  : "justify-start"
              }`}
            >
              <span
                className={`menu-item-icon-size inline-flex items-center justify-center ${
                  openSubmenu?.type === menuType && openSubmenu?.index === index
                    ? "menu-item-icon-active"
                    : "menu-item-icon-inactive"
                }`}
              >
                {nav.icon}
              </span>
              {(isExpanded || isHovered || isMobileOpen) && (
                <span className="menu-item-text whitespace-nowrap">{nav.name}</span>
              )}
              {(isExpanded || isHovered || isMobileOpen) && (
                <FiChevronDown
                  className={`ml-auto w-5 h-5 transition-transform duration-200 ${
                    openSubmenu?.type === menuType &&
                    openSubmenu?.index === index
                      ? "rotate-180 text-brand-500"
                      : ""
                  }`}
                />
              )}
            </button>
          ) : (
            nav.path && (
              <Link
                to={nav.path}
                className={`menu-item group ${
                  isActive(nav.path) ? "menu-item-active" : "menu-item-inactive"
                } flex w-full items-center gap-3 ${
                  !isExpanded && !isHovered
                    ? "justify-center"
                    : "justify-start"
                }`}
              >
                <span
                  className={`menu-item-icon-size inline-flex items-center justify-center ${
                    isActive(nav.path)
                      ? "menu-item-icon-active"
                      : "menu-item-icon-inactive"
                  }`}
                >
                  {nav.icon}
                </span>
                {(isExpanded || isHovered || isMobileOpen) && (
                  <span className="menu-item-text whitespace-nowrap">{nav.name}</span>
                )}
              </Link>
            )
          )}
          {nav.subItems && (isExpanded || isHovered || isMobileOpen) && (
            <div
              ref={(el) => {
                subMenuRefs.current[`${menuType}-${index}`] = el;
              }}
              className="overflow-hidden transition-all duration-300"
              style={{
                height:
                  openSubmenu?.type === menuType && openSubmenu?.index === index
                    ? `${subMenuHeight[`${menuType}-${index}`]}px`
                    : "0px",
              }}
            >
              <ul className="mt-2 space-y-1 ml-9">
                {nav.subItems.map((subItem) => (
                  <li key={subItem.name}>
                    <Link
                      to={subItem.path}
                      className={`menu-dropdown-item ${
                        isActive(subItem.path)
                          ? "menu-dropdown-item-active"
                          : "menu-dropdown-item-inactive"
                      }`}
                    >
                      {subItem.name}
                      <span className="flex items-center gap-1 ml-auto">
                        {subItem.new && (
                          <span
                            className={`ml-auto ${
                              isActive(subItem.path)
                                ? "menu-dropdown-badge-active"
                                : "menu-dropdown-badge-inactive"
                            } menu-dropdown-badge`}
                          >
                            new
                          </span>
                        )}
                        {subItem.pro && (
                          <span
                            className={`ml-auto ${
                              isActive(subItem.path)
                                ? "menu-dropdown-badge-active"
                                : "menu-dropdown-badge-inactive"
                            } menu-dropdown-badge`}
                          >
                            pro
                          </span>
                        )}
                      </span>
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </li>
      ))}
    </ul>
  );

  return (
    <aside
      className={`fixed mt-16 flex flex-col lg:mt-0 top-0 px-5 left-0 bg-white dark:bg-gray-900 dark:border-gray-800 text-gray-900 h-screen transition-all duration-300 ease-in-out z-50 border-r border-gray-200 
        ${
          isExpanded || isMobileOpen
            ? "w-[290px]"
            : isHovered
            ? "w-[290px]"
            : "w-[90px]"
        }
        ${isMobileOpen ? "translate-x-0" : "-translate-x-full"}
        lg:translate-x-0`}
      onMouseEnter={() => !isExpanded && setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <div
        className={`py-8 flex ${
          !isExpanded && !isHovered ? "lg:justify-center" : "justify-start"
        }`}
      >
        <Link to={branding?.href ?? "/"}>
          {isExpanded || isHovered || isMobileOpen ? (
            branding?.expandedLightSrc && branding?.expandedDarkSrc ? (
              <>
                <img
                  className="dark:hidden"
                  src={branding.expandedLightSrc}
                  alt={branding.alt ?? "Logo"}
                  width={branding.expandedWidth ?? 150}
                  height={branding.expandedHeight ?? 40}
                />
                <img
                  className="hidden dark:block"
                  src={branding.expandedDarkSrc}
                  alt={branding.alt ?? "Logo"}
                  width={branding.expandedWidth ?? 150}
                  height={branding.expandedHeight ?? 40}
                />
              </>
            ) : (
              <div className="h-10 w-[150px] rounded-lg bg-gray-100 dark:bg-white/[0.03]" />
            )
          ) : branding?.collapsedSrc ? (
            <img
              src={branding.collapsedSrc}
              alt={branding.alt ?? "Logo"}
              width={branding.collapsedSize ?? 32}
              height={branding.collapsedSize ?? 32}
            />
          ) : (
            <div className="h-8 w-8 rounded-lg bg-gray-100 dark:bg-white/[0.03]" />
          )}
        </Link>
      </div>
      <div className="flex flex-1 flex-col overflow-y-auto duration-300 ease-linear no-scrollbar">
        <nav className="mb-6">
          <div className="flex flex-col gap-4">
            <div>
              <h2
                className={`mb-4 text-xs uppercase flex leading-[20px] text-gray-400 ${
                  !isExpanded && !isHovered
                    ? "lg:justify-center"
                    : "justify-start"
                }`}
              >
                {isExpanded || isHovered || isMobileOpen ? (
                  "Menu"
                ) : (
                  <FiMoreHorizontal className="size-6" />
                )}
              </h2>
              {renderMenuItems(navItems, "main")}
            </div>
            <div className="">
              {hasOthersSection ? (
                <>
                  <h2
                    className={`mb-4 text-xs uppercase flex leading-[20px] text-gray-400 ${
                      !isExpanded && !isHovered
                        ? "lg:justify-center"
                        : "justify-start"
                    }`}
                  >
                    {isExpanded || isHovered || isMobileOpen ? (
                      "Others"
                    ) : (
                      <FiMoreHorizontal className="size-6" />
                    )}
                  </h2>
                  {renderMenuItems(othersItems, "others")}
                </>
              ) : null}
            </div>
          </div>
        </nav>
        {isExpanded || isHovered || isMobileOpen ? <SidebarWidget /> : null}
      </div>

      <div className="pb-6">
        <AppVersion>
          {(info) => {
            const isOpen = isExpanded || isHovered || isMobileOpen;

            if (isOpen) {
              return (
                <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-800 text-xs text-gray-500">
                  <div className="flex flex-col gap-1">
                    <div>
                      <span className="font-medium">App Version :</span> {info.appVersion}
                    </div>
                    {info.showDetailed && (
                      <>
                        <div>
                          <span className="font-medium">Frontend:</span> {info.frontend.version}
                          <span> ({info.frontend.buildTime})</span>
                        </div>
                        <div>
                          <span className="font-medium">Backend:</span> {info.backend.version}
                          <span> ({info.backend.buildTime})</span>
                        </div>
                        <div>
                          <span className="font-medium">environment</span> {info.environment.label}
                        </div>
                      </>
                    )}
                  </div>
                </div>
              );
            }

            return (
              <div className="relative mt-3 pt-3 border-t border-gray-200 dark:border-gray-800 flex justify-center">
                <div className="group relative">
                  <div className="h-7 w-7 rounded-full border border-gray-300 dark:border-gray-700 text-gray-600 dark:text-gray-300 flex items-center justify-center text-xs font-semibold select-none cursor-default">
                    i
                  </div>
                  <div className="pointer-events-none absolute left-full ml-3 bottom-0 hidden group-hover:block z-50">
                    <div className="min-w-[240px] rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2 shadow-lg">
                      <div className="text-xs text-gray-500">
                        <div>
                          <span className="font-medium">App Version :</span> {info.appVersion}
                        </div>
                        <div>
                          <span className="font-medium">Frontend:</span> {info.frontend.version}
                          <span> ({info.frontend.buildTime})</span>
                        </div>
                        <div>
                          <span className="font-medium">Backend:</span> {info.backend.version}
                          <span> ({info.backend.buildTime})</span>
                        </div>
                        <div>
                          <span className="font-medium">environment</span> {info.environment.label}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            );
          }}
        </AppVersion>
      </div>
    </aside>
  );
};

export default AppSidebar;

// HPA.SurveyFlow.Web/src/app/template/tail-admin/layout/app-sidebar.component.ts
import { Component, Input, computed, inject, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive, Router } from '@angular/router';
import { SidebarService } from '../services/sidebar.service';
import { environment } from '../../../../environments/environment';

export interface NavItem {
  name: string;
  path?: string;
  icon: string; // SVG path d attribute
  iconViewBox?: string;
  subItems?: { name: string; path: string }[];
}

export interface SidebarBranding {
  href?: string;
  expandedLightSrc?: string;
  expandedDarkSrc?: string;
  collapsedSrc?: string;
  alt?: string;
  expandedWidth?: number;
  expandedHeight?: number;
  collapsedSize?: number;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  template: `
    <aside
      [class]="sidebarClass()"
      (mouseenter)="onMouseEnter()"
      (mouseleave)="onMouseLeave()"
    >
      <!-- Logo -->
      <div class="py-8 flex" [class.justify-center]="!showLabels()" [class.justify-start]="showLabels()">
        <a [routerLink]="branding?.href ?? '/'">
          @if (showLabels()) {
            @if (branding?.expandedLightSrc) {
              <img
                class="dark:hidden"
                [src]="branding!.expandedLightSrc"
                [alt]="branding?.alt ?? 'Logo'"
                [width]="branding?.expandedWidth ?? 150"
                [height]="branding?.expandedHeight ?? 40"
              />
              <img
                class="hidden dark:block"
                [src]="branding?.expandedDarkSrc ?? branding!.expandedLightSrc"
                [alt]="branding?.alt ?? 'Logo'"
                [width]="branding?.expandedWidth ?? 150"
                [height]="branding?.expandedHeight ?? 40"
              />
            } @else {
              <div class="h-10 w-36 rounded-lg bg-gray-100 dark:bg-white/5 flex items-center justify-center">
                <span class="text-sm font-bold text-gray-700 dark:text-white">SurveyFlow</span>
              </div>
            }
          } @else {
            @if (branding?.collapsedSrc) {
              <img
                [src]="branding!.collapsedSrc"
                [alt]="branding?.alt ?? 'Logo'"
                [width]="branding?.collapsedSize ?? 32"
                [height]="branding?.collapsedSize ?? 32"
              />
            } @else {
              <div class="h-8 w-8 rounded-lg bg-brand-500 flex items-center justify-center">
                <span class="text-xs font-bold text-white">SF</span>
              </div>
            }
          }
        </a>
      </div>

      <!-- Nav -->
      <div class="flex flex-1 flex-col overflow-y-auto no-scrollbar">
        <nav class="mb-6" aria-label="Main navigation">
          <div class="flex flex-col gap-4">
            <div>
              <h2 class="mb-4 text-xs uppercase leading-5 text-gray-400 flex"
                  [class.justify-center]="!showLabels()">
                @if (showLabels()) {
                  <span>Menu</span>
                } @else {
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                    <circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>
                  </svg>
                }
              </h2>
              <ul class="flex flex-col gap-1">
                @for (item of navItems; track item.name) {
                  <li>
                    @if (item.path) {
                      <a
                        [routerLink]="item.path"
                        routerLinkActive="menu-item-active"
                        [routerLinkActiveOptions]="{ exact: item.path === '/admin' || item.path === '/' }"
                        class="menu-item group"
                        [class.menu-item-inactive]="true"
                        [class.justify-center]="!showLabels()"
                        [title]="!showLabels() ? item.name : ''"
                        #rla="routerLinkActive"
                      >
                        <span class="inline-flex items-center justify-center w-6 h-6 shrink-0"
                              [class.menu-item-icon-active]="rla.isActive"
                              [class.menu-item-icon-inactive]="!rla.isActive">
                          <svg class="w-6 h-6" fill="none" stroke="currentColor"
                               [attr.viewBox]="item.iconViewBox ?? '0 0 24 24'">
                            @for (d of item.icon.split('|'); track $index) {
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" [attr.d]="d" />
                            }
                          </svg>
                        </span>
                        @if (showLabels()) {
                          <span class="whitespace-nowrap">{{ item.name }}</span>
                        }
                      </a>
                    }
                  </li>
                }
              </ul>
            </div>
          </div>
        </nav>

        <div
          class="mt-auto border-t border-gray-200 pt-4 text-gray-500 dark:border-gray-800 dark:text-gray-400"
          [class.text-center]="!showLabels()"
          [title]="versionTitle()"
        >
          @if (showLabels()) {
            <div class="text-xs font-medium leading-5">
              v{{ appVersion }}
            </div>
            @if (showEnvironment()) {
              <div class="text-[11px] leading-4 uppercase tracking-wide">
                {{ appEnvironment }}
              </div>
            }
          } @else {
            <div class="mx-auto flex h-8 w-8 items-center justify-center rounded-lg bg-gray-100 text-[11px] font-semibold text-gray-600 dark:bg-white/5 dark:text-gray-300">
              v
            </div>
          }
        </div>
      </div>
    </aside>

    <!-- Mobile backdrop -->
    @if (sidebar.isMobileOpen()) {
      <div
        class="fixed inset-0 z-40 bg-gray-900/50 lg:hidden"
        (click)="sidebar.toggleMobileSidebar()"
      ></div>
    }
  `,
})
export class AppSidebarComponent {
  @Input() navItems: NavItem[] = [];
  @Input() branding?: SidebarBranding;

  sidebar = inject(SidebarService);
  readonly appVersion = environment.appVersion?.trim() || 'local';
  readonly appEnvironment = environment.appEnvironment?.trim() || 'development';

  showLabels = computed(() =>
    this.sidebar.isExpanded() || this.sidebar.isHovered() || this.sidebar.isMobileOpen()
  );

  showEnvironment = computed(() => this.appEnvironment.toLowerCase() !== 'production');

  versionTitle = computed(() => {
    const environmentSuffix = this.showEnvironment() ? ` (${this.appEnvironment})` : '';
    return `Version ${this.appVersion}${environmentSuffix}`;
  });

  sidebarClass = computed(() => {
    const expanded = this.sidebar.isExpanded();
    const hovered = this.sidebar.isHovered();
    const mobileOpen = this.sidebar.isMobileOpen();

    const width = expanded || hovered ? 'w-[290px]' : 'w-[90px]';
    const mobileTranslate = mobileOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0';

    return `fixed top-0 left-0 px-5 h-screen flex flex-col bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-800 transition-all duration-300 ease-in-out z-50 ${width} ${mobileTranslate}`;
  });

  constructor() {
    effect(() => {
      const expanded = this.sidebar.isExpanded();
      const hovered = this.sidebar.isHovered();
      const w = expanded || hovered ? '290px' : '90px';
      document.documentElement.style.setProperty('--sidebar-width', w);
    });
  }

  onMouseEnter(): void {
    if (!this.sidebar.isExpanded()) {
      this.sidebar.setHovered(true);
    }
  }

  onMouseLeave(): void {
    this.sidebar.setHovered(false);
  }
}
